
# Training parameters
learning_rate: 0.001
num_epochs: 20
batch_size: 16

# Optimizer parameters
# https://www.kaggle.com/code/ripupz/carsidentifier/notebook
# Model parameters

# Data paths
train_images_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/cars_train/cars_train"
test_images_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/cars_test/cars_test"
test_csv_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/stanford_cars_with_class_names_test.csv"
train_csv_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/stanford_cars_with_class_names_train.csv"
car_names_csv: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/cars_annotations_with_names.csv"
model_save_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition"
# Other
# fix me find dynamically
num_classes: 1716
num_car_makes: 163