
# Training parameters
learning_rate: 0.001
num_epochs: 20
batch_size: 16

# Optimizer parameters
# https://www.kaggle.com/code/ripupz/carsidentifier/notebook
# Model parameters

# Data paths
train_txt_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/compcars/data/train_test_split/classification/train.txt"
test_txt_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/compcars/data/train_test_split/classification/test.txt"
test_csv_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/stanford_cars_with_class_names_test.csv"
train_csv_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/stanford_cars_with_class_names_train.csv"
car_names_csv: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/cars_annotations_with_names.csv"
model_save_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition"
json_dict_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/combined_mapping.json"
final_model_path: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/final_model.pth"
make_model_name_mat: "C:/Users/seanf/Desktop/School/Pattern Recognition/CarModelRecognition/data/compcars/data/misc/make_model_name.mat"
# Other
# fix me find dynamically
num_classes: 1716
num_car_makes: 163